//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bandwidth.Net.Test {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///    A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Json {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal Json() {
        }
        
        /// <summary>
        ///    Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Bandwidth.Net.Test.Json", typeof(Json).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///    Overrides the current thread's CurrentUICulture property for all
        ///    resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to {&quot;balance&quot;: &quot;538.37250&quot;,&quot;accountType&quot;:&quot;pre-pay&quot;}.
        /// </summary>
        public static string Account {
            get {
                return ResourceManager.GetString("Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to [{&quot;id&quot;: &quot;transactionId1&quot;, &quot;time&quot;: &quot;2013-02-21T13:39:09Z&quot;,&quot;amount&quot;: &quot;0.00750&quot;,&quot;type&quot;: &quot;charge&quot;,&quot;units&quot;: &quot;1&quot;,&quot;productType&quot;: &quot;sms-out&quot;,&quot;number&quot;: &quot;1234567890&quot;}].
        /// </summary>
        public static string AccountTransactions {
            get {
                return ResourceManager.GetString("AccountTransactions", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to {
        ///    &quot;id&quot;: &quot;applicationId&quot;,
        ///    &quot;name&quot;: &quot;MyFirstApp&quot;,
        ///    &quot;incomingCallUrl&quot;: &quot;http://example.com/calls.php&quot;,
        ///    &quot;incomingMessageUrl&quot;: &quot;http://example.com/messages.php&quot;,
        ///    &quot;autoAnswer&quot;: true
        ///  }.
        /// </summary>
        public static string Application {
            get {
                return ResourceManager.GetString("Application", resourceCulture);
            }
        }
    }
}
